name: 'Broadcast update'

on:
  push:
    branches:
      - main    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  notify:
    name: 'Submodule Notify Parent'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['haihodac-pepperstone/bookish-funicular']
    steps:
      - name: Repository Dispatches
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.BROADCAST_PAT }}
          # repository: haihodac-pepperstone/bookish-funicular
          repository: ${{ matrix.repo }}
          event-type: submodule-update
          client-payload: '{"author": "${{ github.actor }}"}'